config/routes.rb
Rails.application.routes.draw do

  resources :transport_hours

  resources :hours

  resources :transports

  resources :weathers

  resources :current_videos

  resources :footer_news

  resources :menus

  resources :free_classrooms

  resources :classrooms

  resources :bookmarked_contents

  resources :user_contents

  resources :scores

  resources :games

  resources :content_videos

  resources :videos

  resources :tag_contents

  resources :tags

  resources :contents

  devise_for :users
  resources :users

  get 'homepage/feeds' => 'homepage#feeds'
  get 'homepage/fetch_mail' => 'homepage#fetch_mail'

  get 'homepage/index'
  get 'tv' => 'tv#show'

  root 'homepage#index'

  get 'homepage/search'

  resources :users do
    resources :scores
    resources :bookmarked_contents
    resources :user_contents
    resources :free_classrooms
    resources :contents
  end

  resources :contents do
    resources :tags
    resources :videos
  end

end

app/models/content.rb
class Content < ActiveRecord::Base

  # has_many :content_videos
  # has_many :videos, through: :content_videos
  has_one :video

  has_many :tag_contents
  has_many :tags, through: :tag_contents

  has_many :bookmarked_contents
  has_many :users, through: :bookmarked_contents

  has_many :user_content
  has_many :users, through: :user_content

  accepts_nested_attributes_for :tags, :video

  validates_uniqueness_of :title, :scope => [:description]

  validates :title, presence: true

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:show, :index]


  # GET /contents
  # GET /contents.json
  def index

    if !current_user.nil?
      temp = current_user.bookmarked_contents
      @user_bookmarked_contents = []

      temp.each do |entry|
        @user_bookmarked_contents.push(entry.content_id)
      end

    end

    if params[:user_id] # GET /users/:id/contents

      @search_only_user_contents = true
      @display_all = false

      if params[:tag][:id] != ""
        @selected_tag = params[:tag][:id]
        @contents = Tag.find(params[:tag][:id]).contents.where(:user_id => current_user.id)
      else
        @selected_tag = ""
        @contents = User.find(params[:user_id]).contents
      end

    else # GET /contents

      puts "============= /contents ============"

      @selected_tag = ""
      @contents = Content.all
      @display_all = true
      @search_only_user_contents = false

      if params[:tag]
        @selected_tag = params[:tag][:id]
        @contents = Tag.find(params[:tag][:id]).contents
      end

    end
  end


# GET /contents/1
# GET /contents/1.json
  def show
    if @content.nil?
      flash[:error] = "O conteúdo que procuras não existe!"
      redirect_to root_url
    else
      @latest = Content.all.order(created_at: :desc).limit(15)

      @author = User.find_by(:id => @content.user_id)
      # puts "LOOOOOOOOOOOOOOOOL"

      puts @content.title
      puts @author.id

      @video = @content.video

      if !(@content.views.nil?)
        @content.views = @content.views + 1
        @content.save
      end
    end
  end

# GET /contents/new
  def new
    @content = Content.new
    @tags = Tag.all
  end

# GET /contents/1/edit
  def edit

    if current_user.nil?
      flash[:error] = "Não tens permissões para realizar essa acção!"
      redirect_to root_url
    else
      if !@content.nil?
        if current_user.id == 1
          #modo admin, permitir edição
        elsif @content.user_id != current_user.id
          flash[:error] = "Não tens permissões para editar esse conteúdo!"
          redirect_to root_url
        end
      else
        flash[:error] = "O conteúdo que procuras não existe!"
        redirect_to root_url
      end
    end

  end

# POST /contents
# POST /contents.json
  def create
    @content = Content.new(content_params)
    @content.date = Date.today
    @content.user_id = current_user.id
    @content.views = 0
    @content.users << current_user

    if params[:link_image].nil?
      @content.link_image = 'fct.gif'
    end

    if !params[:video].nil?
      Video.create(:link => params[:video][:link_video])
      @content.video = Video.find_by(:link => params[:video][:link_video])
    end

    params[:content][:tag_ids].each do |tag|
      if tag != ""
        @content.tags << Tag.find(tag)
      end

    end


    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

# PATCH/PUT /contents/1
# PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

# DELETE /contents/1
# DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_content
    @user_id = -1
    if params[:title]
      @content = Content.where(title: params[:title]).first
    else
      # count = Content.count
      exists = Content.exists?(params[:id].to_i)
      if exists
        # puts ":::::::::::::::::::::::::::::::::::::"
        @content = Content.find(params[:id])
        @user_id = params[:user_id].to_i
      end
    end
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def content_params
    params.require(:content).permit(:title, :link_image, :description, :news_text, :link, tag_ids: [:id])
  end

end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= simple_form_for(@content) do |f| %>
    <% if @content.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

          <ul>
            <% @content.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :titulo %>
      <br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="field form-group">
      <%= f.label :link_imagem %>
      <br>
      <%= f.text_field :link_image, class: 'form-control' %>
    </div>

    <div class="field form-group">
      <%= f.label :descrição %>
      <br>
      <%= f.text_area :description, class: 'form-control' %>
    </div>



    <div class="field form-group">
      <%= f.label :texto_da_noticia %>
      <br>
      <%= f.text_area :news_text, class: 'form-control' %>
    </div>

    <div class="field form-group">
      <%= f.association :tags, label_method: :tag, value_method: :id, as: :check_boxes, :item_wrapper_class => 'checkbox_container' %>
      <%#= f.collection_check_boxes :id, Tag.all, :value_method, :text_method, :item_wrapper_class => 'checkbox_container' %>
    </div>


    <%= simple_fields_for :video do |v| %>
        <%= v.input :link_video, required: false %>
    <% end %>

    <div class="actions" style="margin-top: 2%">
      <%= f.submit 'Adicionar conteudo', class: "btn btn-default" %>
    </div>

<% end %>

app/views/contents/edit.html.erb
<div id="cont1" class="container space-top space-bottom">
  <h1 class="page-header">Editar Notícia</h1>

  <%= render 'form' %>
  <p></p>
  <%= button_to 'Voltar atrás', contents_path, method: :get, class: "btn btn-default" %>
  <p></p>

</div>

app/views/contents/index.html.erb
<style>
    #description {
        margin-top: 10px;
        margin-bottom: 10px;
    }
</style>

<div id="cont1" class="container space-top space-bottom" style="padding-bottom: 3%">
  <% if user_signed_in? %>
      <% if @display_all.nil? %>
          <h1 class="page-header">Os meus conteúdos</h1>
      <% else %>
          <h1 class="page-header">Notícias</h1>
      <% end %>
  <% else %>
      <h1 class="page-header">Notícias</h1>
  <% end %>


  <div class="row">

    <% if @search_only_user_contents %>
        <%= form_tag("/users/#{current_user.id}/contents", :method => "get", id: "building-form") do %>
            <div class="col-xs-5 col-md-3">
              <%= collection_select :tag, :id, Tag.all, :id,
                                    :tag, {:selected => @selected_tag, include_blank: 'Todas'}, class: 'form-control' %>
            </div>
            <div class="col-md-2">
              <%= submit_tag "Filtrar", class: 'btn btn-default' %>
            </div>
        <% end %>
    <% else %>
        <%= form_tag(contents_path, :method => "get", id: "building-form") do %>
            <%= hidden_field_tag :id_user, @user_id %>
            <div class="col-xs-5 col-md-3">
              <%= collection_select :tag, :id, Tag.all, :id,
                                    :tag, {:selected => @selected_tag, include_blank: 'Todas'}, class: 'form-control' %>
            </div>
            <div class="col-md-2">
              <%= submit_tag "Filtrar", class: 'btn btn-default' %>
            </div>
        <% end %>
    <% end %>

    <div class="col-md-3">
      <% if user_signed_in? %>
          <%= button_to('Adicionar nova noticia', new_content_path, method: :get, class: "btn btn-default") %>
      <% end %>
    </div>
  </div>

  <br>

  <% if @contents.size > 0 %>
      <table class="table table-hover table-striped">
        <tr>
          <th class="col-md-1" style="text-align: center">Link imagem</th>
          <th class="col-md-3" style="text-align: center">Título</th>
          <th class="col-md-5" style="text-align: center">Descrição</th>
          <th class="col-md-1">Agendar para depois</th>
          <th class="col-md-1" style="text-align: center">Data de inserção</th>
          <th class="col-md-1">Visualizações</th>
        </tr>
        <% @contents.each do |content| %>
            <tr>
              <td class="col-md-1"><%= link_to (image_tag content.link_image, size: '90x70'), content_path(content.id) %></td>
              <td class="col-md-3"><%= raw link_to content.title, content_path(content.id) %></td>
              <td id="description" class="col-md-5"><%= raw content.description %></td>
              <% if current_user.nil? %>
                  <td class="col-md-1">
                    <button type="button" disabled class="btn btn-default btn-lg navbar-btn" onclick="">
                      <span class="glyphicon glyphicon-time"></span>
                    </button>
                  </td>
              <% else %>
                  <td class="col-md-1">
                    <% if @user_bookmarked_contents.include? content.id %>
                        <button type="button" disabled class="btn btn-default btn-lg navbar-btn">
                          <span class="glyphicon glyphicon-time"></span>
                        </button>
                    <% else %>
                        <%= link_to raw("<i class=\"glyphicon glyphicon-time\"></i>"), contents_path,
                                    onclick: "watchLater(" + content.id.to_s + ")", class: 'btn btn-success btn-lg navbar-btn' %>
                    <% end %>
                  </td>
              <% end %>
              <td class="col-md-1" style="text-align: center"><%= content.created_at.strftime("%d/%m/%Y, %H:%M") %></td>
              <td class="col-md-1" style="text-align: center"><%= content.views %></td>
            </tr>
        <% end %>
      </table>
  <% else %>
      <strong><p>Ainda não adicionaste nenhuma notícia.<br>
        Adiciona uma clicando no botão acima!</p></strong>
  <% end %>
</div>

app/views/contents/new.html.erb
<div id="cont1" class="container space-top space-bottom" style="padding-bottom: 3%">
  <h1 class="page-header">Adicionar conteúdo</h1>

  <%= render 'form' %>
  <p></p>
  <%= button_to('Voltar atrás', contents_path, method: :get, class: "btn btn-default") %>
  <p></p>
</div>

app/views/contents/show.html.erb
<div id="cont1" class="container space-top space-bottom" style="padding-bottom: 3%">

  <style>
      .tag-styled {
          background-color: lightblue;
          border-radius: 50px;
          padding: 5px;
          margin-right: 5px
      }

      .tag-styled a {
          color: blue;
      }

      p {
          font-size: 110%;
          font-family: "Myriad Pro Regular";
      }

      .image-style {
          width: 100%;
          height: 100%;
          margin-top: 10px;
          margin-bottom: 20px;
      }

      .space-in-between {
          margin-top: 15px;
          margin-bottom: 15px;
      }

      .btn-group {
          display: inline-block;
      }

      .line-spacing {
          line-height: 23px;
      }

  </style>

  <div class="row">
    <div class="col-md-8">

      <h3 class="row col-md-12">
        <b><%= raw @content.title %></b>
      </h3>

      <div class="row col-md-12" style="font-size: 90%; margin-bottom: 20px">
        <p class="space-in-between">
          <%= raw @content.description %>
        </p>
      </div>

      <div class="row" style="">

        <div class="col-md-3">
          <strong><span class="glyphicon glyphicon-calendar"></span></strong>
          <% time = @content.created_at %>
          <%= time.strftime("%d/%m/%Y, às %H:%M") %>
        </div>

        <div class="col-md-2">
          <strong><span class="glyphicon glyphicon-eye-open"></span></strong>
          <% views = @content.views %>
          <% if views == 1 %>
              <strong> <%= views %> viu</strong>
          <% else %>
              <strong> <%= views %> viram</strong>
          <% end %>
        </div>

        <div class="col-md-4">
          <strong><span class="glyphicon glyphicon-user"></span></strong>
          <%= link_to @author.name, @author, method: :get %>
        </div>
      </div>

      <div class="row" style="margin-top: 10px; margin-bottom: 10px;">
        <div class="col-md-10">
          <span class="glyphicon glyphicon-tag"></span>
          <% if @content.tags.size > 0 %>
              <% @content.tags.each do |tag| %>
                  <span class="tag-styled"><%= link_to tag.tag, '#' %></span>
              <% end %>
          <% else %>
              <span>Este conteúdo não nenhuma tag associada!</span>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-10">
          <%= image_tag @content.link_image, class: 'img-rounded image-style' %>
        </div>
      </div>

      <div class="row">
        <p class="col-md-12 line-spacing">
          <%= raw @content.news_text %>
        </p>
      </div>


      <% if !@video.nil? %>
          <div class="row" style="margin-top: 15px; margin-bottom: 15px">
            <iframe class="col-md-10" src="<%= @video.link %>"
                    style="width: 100%; height:500px; border: 0px; padding: 0px"
                    allowfullscreen="">

            </iframe>


            <!--<iframe class="col-md-10" src="video.link + ?autoplay=1&controls=0&modestbranding=1&showinfo=0" style="width: 100%; height:100%;"-->
            <!--frameborder="0"-->
            <!--width=100%-->
            <!--height:-->
            <!--100%-->
            <!--enablejsapi="1"-->
            <!--allowfullscreen >-->
            <!--</iframe>-->
          </div>
      <% end %>


      <div class="row" style="margin-top: 30px">
        <% if !current_user.nil? %>
            <% if (@author.id == current_user.id) or (current_user.id == 1) %>
                <div class="col-md-2">
                  <%= button_to 'Editar notícia', edit_content_path(@content), method: :get, class: "btn btn-default" %>
                </div>
                <div class="col-md-3">
                  <%= button_to 'Remover notícia', @content, method: :delete, data: {confirm: 'Tens a certeza que queres remover esta notícia?'}, class: "btn btn-default" %>
                </div>
            <% end %>
        <% end %>
        <div class="col-md-3">
          <%= button_to 'Voltar atrás', contents_path, method: :get, class: "btn btn-default" %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <h2 class="table-header" style="text-align: center">Notícias mais recentes</h2>
      <table class="table table-hover">
        <% @latest.each do |content| %>
            <tr>
              <td><%= link_to content.title, content, method: :get %></td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>

</div>