config/routes.rb
Rails.application.routes.draw do

  resources :transport_hours

  resources :hours

  resources :transports

  resources :weathers

  resources :current_videos

  resources :footer_news

  resources :menus

  resources :free_classrooms

  resources :classrooms

  resources :bookmarked_contents

  resources :user_contents

  resources :scores

  resources :games

  resources :content_videos

  resources :videos

  resources :tag_contents

  resources :tags

  resources :contents

  devise_for :users
  resources :users

  get 'homepage/feeds' => 'homepage#feeds'
  get 'homepage/fetch_mail' => 'homepage#fetch_mail'

  get 'homepage/index'
  get 'tv' => 'tv#show'

  root 'homepage#index'

  get 'homepage/search'

  resources :users do
    resources :scores
    resources :bookmarked_contents
    resources :user_contents
    resources :free_classrooms
    resources :contents
  end

  resources :contents do
    resources :tags
    resources :videos
  end

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base

  has_many :free_classrooms

  validate :building, presence: true
  validate :classroom, presence: true
  validate :classroom, uniqueness: true

end

app/models/content.rb
class Content < ActiveRecord::Base

  # has_many :content_videos
  # has_many :videos, through: :content_videos
  has_one :video

  has_many :tag_contents
  has_many :tags, through: :tag_contents

  has_many :bookmarked_contents
  has_many :users, through: :bookmarked_contents

  has_many :user_content
  has_many :users, through: :user_content

  accepts_nested_attributes_for :tags, :video

  validates_uniqueness_of :title, :scope => [:description]

  validates :title, presence: true

end

app/models/footer_news.rb
class FooterNews < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base

  #has_many :users
  has_many :scores

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/hour.rb
class Hour < ActiveRecord::Base

  has_many :transport_hours
  has_many :transports, through: :transport_hours

  validates :hour, presence: true
  validates :minute, presence: true
end

app/models/menu.rb
class Menu < ActiveRecord::Base

  validates_uniqueness_of :dish, :scope => [:meal, :restaurant, :date]

end

app/models/score.rb
class Score < ActiveRecord::Base

  belongs_to :game
  belongs_to :user

  validates :score, presence: true
  validates_associated :game, :user
  validates_presence_of :game, :user

  validates_uniqueness_of :game_id, :scope => [:user_id]
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :tag_contents
  has_many :contents, through: :tag_contents

  validates :tag, presence: true;
  validates_associated :contents

end

app/models/tag_content.rb
class TagContent < ActiveRecord::Base

  belongs_to :content
  belongs_to :tag


  validates_associated :tag
  validates_associated :content

  validates_presence_of :tag
  validates_presence_of :content
end

app/models/transport.rb
class Transport < ActiveRecord::Base

  has_many :transport_hours
  has_many :hours, through: :transport_hours

  validates :carreira, presence: true
  validates :origin, presence: true
  validates :destination, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :bookmarked_contents
  has_many :contents, through: :bookmarked_contents

  has_many :user_contents
  has_many :contents, through: :user_contents

  has_many :user_votes
  has_many :free_classrooms, through: :user_votes
  #has_many :classrooms, through: :free_classrooms

  has_many :scores
  #has_many :games, through: :scores

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :gender, presence: true
  validates :course, presence: true
  validates :birth_date, presence: true

  validates :email, format: {with: /\b[A-Z0-9._%a-z\-]+@(campus.)?fct\.unl\.pt\z/,
                             message: "Tem de usar o email @campus.fct.unl.pt"}
end

app/models/user_content.rb
class UserContent < ActiveRecord::Base

  belongs_to :user
  belongs_to :content

  validates_associated :user, :content

  validates_presence_of :user, :content
end

app/models/user_vote.rb
class UserVote < ActiveRecord::Base

  belongs_to :user
  belongs_to :free_classroom

  validates_uniqueness_of :user_id, :scope => [:free_classroom_id],
                          :message => 'Esta sala já existe'

end

app/models/video.rb
class Video < ActiveRecord::Base

  # has_many :contents, through: :content_videos
  belongs_to :content

  validates :link, presence: true;
  validates_associated :content
end

app/models/weather.rb
class Weather < ActiveRecord::Base

  validates_uniqueness_of :date, :scope => [:min_temp, :max_temp]

end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :set_transport, only: [:show, :edit, :update, :destroy]

  # GET /transports
  # GET /transports.json
  def index
    @transports = Transport.all


    respond_to do |format|
      format.json { render :json => @transports.to_json(:include => [:transport_hours, :hours]) }
    end
  end

  # GET /transports/1
  # GET /transports/1.json
  def show
  end

  # GET /transports/new
  def new
    @transport = Transport.new
  end

  # GET /transports/1/edit
  def edit
  end

  # POST /transports
  # POST /transports.json
  def create
    @transport = Transport.new(transport_params)

    respond_to do |format|
      if @transport.save
        format.html { redirect_to @transport, notice: 'Transport was successfully created.' }
        format.json { render :show, status: :created, location: @transport }
      else
        format.html { render :new }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transports/1
  # PATCH/PUT /transports/1.json
  def update
    respond_to do |format|
      if @transport.update(transport_params)
        format.html { redirect_to @transport, notice: 'Transport was successfully updated.' }
        format.json { render :show, status: :ok, location: @transport }
      else
        format.html { render :edit }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transports/1
  # DELETE /transports/1.json
  def destroy
    @transport.destroy
    respond_to do |format|
      format.html { redirect_to transports_url, notice: 'Transport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_transport
    @transport = Transport.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def transport_params
    params.require(:transport).permit(:carreira, :origin, :destination)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/helpers/tv_helper.rb
module TvHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/transports/_form.html.erb
<%= form_for(@transport) do |f| %>
  <% if @transport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transport.errors.count, "error") %> prohibited this transport from being saved:</h2>

      <ul>
      <% @transport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :carreira %><br>
    <%= f.number_field :carreira %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transports/edit.html.erb
<h1>Editing transport</h1>

<%= render 'form' %>

<%= link_to 'Show', @transport %> |
<%= link_to 'Back', transports_path %>

app/views/transports/index.html.erb
<h1>Listing transports</h1>

<table>
  <thead>
    <tr>
      <th>Carreira</th>
      <th>Origin</th>
      <th>Destination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transports.each do |transport| %>
      <tr>
        <td><%= transport.carreira %></td>
        <td><%= transport.origin %></td>
        <td><%= transport.destination %></td>
        <td><%= link_to 'Show', transport %></td>
        <td><%= link_to 'Edit', edit_transport_path(transport) %></td>
        <td><%= link_to 'Destroy', transport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transport', new_transport_path %>

app/views/transports/new.html.erb
<h1>New transport</h1>

<%= render 'form' %>

<%= link_to 'Back', transports_path %>

app/views/transports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Carreira:</strong>
  <%= @transport.carreira %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @transport.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @transport.destination %>
</p>

<%= link_to 'Edit', edit_transport_path(@transport) %> |
<%= link_to 'Back', transports_path %>